### Configuration
# admin: is the url of the ejabberd admin interface
# domain: the xmpp domain to use
# bosh: the url of the bosh service
# xmpp: disable xmpp 


defaults: &defaults
  admin: http://admin:admin@psi:5280/admin/server/psi
  bosh: http://localhost:5280/http-bind
  domain: psi
  xmpp: true

development:
  <<: *defaults

test:
  <<: *defaults

production:
  <<: *defaults
  admin: http://admin:admin@box:5280/admin/server/box
  bosh: http://www.mobilesynergies.org/xmpp-httpbind
  domain: box
